# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7dd3757149fecc7553da9b90810bbbae5c888b2fcacfb5c9c4ba0e72e21fb8daaef56676b1f5914b2acd5294cb4b41a4cd84ec99495ae1ed303a29feda473d7d

test:
  secret_key_base: 223ccba99bc6512ca3530dd70167eba2f3d277b2aa5c357054e146ed070e7116172466d07d915287e31230839a412f57aebc62fe98355dcdbdb3b70d5c306edf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
